// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCXPnBSWk6nHXAAM6gInghPFHWKLhHRmeY',
    appId: '1:929047935917:web:353d9a90fc7023aa703f24',
    messagingSenderId: '929047935917',
    projectId: 'moodlens-ai-b609f',
    authDomain: 'moodlens-ai-b609f.firebaseapp.com',
    storageBucket: 'moodlens-ai-b609f.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBW_l9PdaKNiXk5MX5d15ncctmGqhgt7Qo',
    appId: '1:929047935917:android:b3c08dcbd2481920703f24',
    messagingSenderId: '929047935917',
    projectId: 'moodlens-ai-b609f',
    storageBucket: 'moodlens-ai-b609f.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCPeYBZk0U6TGn8o1DmxCAfcnmxGswHn9A',
    appId: '1:929047935917:ios:fec29a2ef87e4c40703f24',
    messagingSenderId: '929047935917',
    projectId: 'moodlens-ai-b609f',
    storageBucket: 'moodlens-ai-b609f.firebasestorage.app',
    iosClientId: '929047935917-lbiqi1nuquhr37qe1poo4afhluk7ib9j.apps.googleusercontent.com',
    iosBundleId: 'com.example.moodlensApp',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCPeYBZk0U6TGn8o1DmxCAfcnmxGswHn9A',
    appId: '1:929047935917:ios:fec29a2ef87e4c40703f24',
    messagingSenderId: '929047935917',
    projectId: 'moodlens-ai-b609f',
    storageBucket: 'moodlens-ai-b609f.firebasestorage.app',
    iosClientId: '929047935917-lbiqi1nuquhr37qe1poo4afhluk7ib9j.apps.googleusercontent.com',
    iosBundleId: 'com.example.moodlensApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCXPnBSWk6nHXAAM6gInghPFHWKLhHRmeY',
    appId: '1:929047935917:web:d7718729839e9b59703f24',
    messagingSenderId: '929047935917',
    projectId: 'moodlens-ai-b609f',
    authDomain: 'moodlens-ai-b609f.firebaseapp.com',
    storageBucket: 'moodlens-ai-b609f.firebasestorage.app',
  );
}
